[theme]
base="light"
primaryColor="lavender"
backgroundColor="white"
secondaryBackgroundColor="powderBlue"
textColor="softCharcoal"
baseRadius="large"
font="times"

[theme.sidebar]
backgroundColor="ghostWhite"
secondaryBackgroundColor="lavender"
font="times"
